### ISSUE TITLE
Figure out how to get this sucker to work

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#4]
Current state of things...

After going through the [Getting Started steps](https://github.com/maybe-finance/marketing?tab=readme-ov-file#getting-started) and running `bin/dev`, I'm getting this error:

```
Error: error:0308010C:digital envelope routines::unsupported
16:42:00 webpack-dev-server.1 |     at new Hash (node:internal/crypto/hash:71:19)
16:42:00 webpack-dev-server.1 |     at Object.createHash (node:crypto:133:10)
16:42:00 webpack-dev-server.1 |     at module.exports (/Users/joshpigford/Development/maybe-marketing/node_modules/webpack/lib/util/createHash.js:135:53)
16:42:00 webpack-dev-server.1 |     at NormalModule._initBuildHash (/Users/joshpigford/Development/maybe-marketing/node_modules/webpack/lib/NormalModule.js:417:16)
16:42:00 webpack-dev-server.1 |     at handleParseError (/Users/joshpigford/Development/maybe-marketing/node_modules/webpack/lib/NormalModule.js:471:10)
16:42:00 webpack-dev-server.1 |     at /Users/joshpigford/Development/maybe-marketing/node_modules/webpack/lib/NormalModule.js:503:5
16:42:00 webpack-dev-server.1 |     at /Users/joshpigford/Development/maybe-marketing/node_modules/webpack/lib/NormalModule.js:358:12
16:42:00 webpack-dev-server.1 |     at /Users/joshpigford/Development/maybe-marketing/node_modules/loader-runner/lib/LoaderRunner.js:373:3
16:42:00 webpack-dev-server.1 |     at iterateNormalLoaders (/Users/joshpigford/Development/maybe-marketing/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
16:42:00 webpack-dev-server.1 |     at /Users/joshpigford/Development/maybe-marketing/node_modules/loader-runner/lib/LoaderRunner.js:186:6
```

And running `npm install` just results in even more errors.

So, any ideas on this would be very welcome.

**Comment by vipulnsward** [comment]
This works on node < 17, since those dependencies are older. Can pin node to 14x or 16x for now till webpacker is updated

![image](https://github.com/maybe-finance/marketing/assets/567626/a6f766fb-ceef-40ce-9685-619e4ea34b87)

**Comment by Shpigford** [comment]
@vipulnsward for a barely functioning idiot like myself...what did you change in the codebase to get that working?

**Comment by Shpigford** [comment]
GPT tells me adding an `.nvmrc` with `16` as the contents does the trick. Which...it does. Hopefully it's that simple. 🙂
